### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by RinRintech** [RinRintech/furima-39853#9]
# 自身のフリマアプリのURL
http://54.249.234.115/

# 出品者用のメールアドレスとパスワード
techcamprin@techcamp.co.jp
rinrin0914

# 購入者用のメールアドレスとパスワード
techcamplen@techcamp.co.jp
lenlen0914

**Comment by mo1015** [comment]
@RinRintech さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態の場合でも、自身が出品した商品の商品購入ページに遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
自身が出品した売却済み商品の商品購入ページに遷移しようとすると、エラーページに遷移してしまいます。

- [x] **購入画面にて、エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
「Phone number can't be blank」というエラーメッセージが重複しています。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by RinRintech** [comment]
mo1015様

ご確認いただき、ありがとうございます！

修正、動作確認完了しましたので
再度フォーム提出いたしました。

お手数おかけいたしますが、
再度のご確認をお願いいたします。

**Comment by mo1015** [comment]
@RinRintech さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![LGTM](https://user-images.githubusercontent.com/54050089/247836744-30ce3d68-a780-451a-9b33-69685126a5e4.png)

**Comment by RinRintech** [comment]
mo1015様

再度ご確認いただき、ありがとうございます！

私がLGTMを頂けたのは、テックキャンプの皆様のおかげです。
本当にありがとうございました。

引き続き、卒業までよろしくお願いいたします！
